#docker-compose.yml (Base)
version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
services:


### ClickHouse #############################################
  clickhouse19:
    build:
      context: ./settings/clickhouse
      args:
        - CLICKHOUSE_VERSION=19.9.2.4
        - CLICKHOUSE_GOSU_VERSION=${CLICKHOUSE_GOSU_VERSION}
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/clickhouse/19.9.2:/var/lib/clickhouse
      - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
      - ${CLICKHOUSE_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "9813:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
      
  clickhouse209:
    build:
      context: ./settings/clickhouse
      args:
        - CLICKHOUSE_VERSION=20.9.4.76
        - CLICKHOUSE_GOSU_VERSION=${CLICKHOUSE_GOSU_VERSION}
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/clickhouse/20.9.4:/var/lib/clickhouse
      - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
      - ${CLICKHOUSE_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "10813:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
      
      
  clickhouse21:
    build:
      context: ./settings/clickhouse
      args:
        - CLICKHOUSE_VERSION=21.9.7.2
        - CLICKHOUSE_GOSU_VERSION=${CLICKHOUSE_GOSU_VERSION}
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/clickhouse/21.9.7:/var/lib/clickhouse
      - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
      - ${CLICKHOUSE_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "11813:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
      
  clickhouse22:
    build:
      context: ./settings/clickhouse
      args:
        - CLICKHOUSE_VERSION=22.2.2.1
        - CLICKHOUSE_GOSU_VERSION=${CLICKHOUSE_GOSU_VERSION}
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/clickhouse/22.2.2:/var/lib/clickhouse
      - ${CLICKHOUSE_CUSTOM_CONFIG}:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_USERS_CUSTOM_CONFIG}:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_HOST_LOG_PATH}:/var/log/clickhouse
      - ${CLICKHOUSE_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "12813:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend